branch-defaults:
  default:
    environment: c2go-api-dev
    group_suffix: null
global:
  application_name: c2go-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: null
